export const SUBMIT_CONTACT = 'SUBMIT_CONTACT';
export const POST_PROMO = 'POST_PROMO';
export const GET_QUOTE = 'GET_QUOTE';
export const LOGIN_MANUAL = 'LOGIN_MANUAL';

//===== GLOBAL ACTIONS =====
export const CHANGE_EVENT = "change";


//===== PET ACTIONS =====
export const CREATE_PET = "CREATE_PET";
export const RESET_PET_CREATION = "RESET_PET_CREATION";
export const INCREMENT_PET_CREATION_STEP = "INCREMENT_PET_CREATION_STEP";
export const SET_PET_CREATION_TRUE = "SET_PET_CREATION_TRUE";
export const UPDATE_PET_CREATION = "UPDATE_PET_CREATION";
export const UPDATE_OWNER_PETS = "UPDATE_OWNER_PETS";
export const UPDATE_SELECTED_PET = "UPDATE_SELECTED_PET";
export const UPDATE_DISCOVERY_PETS = "UPDATE_DISCOVERY_PETS";
export const ADD_DISCOVERY_PETS = "ADD_DISCOVERY_PETS";
export const ADD_PET_COMMENTS = "ADD_PET_COMMENTS";
export const SET_PET_COMMENTS = "SET_PET_COMMENTS";
export const SET_PET_DISPLAY = "SET_PET_DISPLAY";
export const ADD_OWNER_PETS = "ADD_OWNER_PETS";

//===== OWNER ACTIONS =====
export const ASSIGN_OWNER = "ASSIGN_OWNER";
export const CREATE_OWNER = "CREATE_OWNER";
export const LOGOUT_OWNER = "LOGOUT_OWNER";
export const CHANGE_FB_LOGIN = "CHANGE_FB_LOGIN";

//===== MESSAGE ACTIONS =====
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const DISMISS_MESSAGE = "DISMISS_MESSAGE";


//===== LOADING ACTIONS =====
export const SET_LOADING = "SET_LOADING";
export const DISMISS_LOADING = "DISMISS_LOADING";

//===== NOTIFICATIONS ACTIONS =====
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const APPEND_NOTIFICATIONS = "APPEND_NOTIFICATIONS";
export const SET_ALL_READ_NOTIFICATIONS = "SET_ALL_READ_NOTIFICATIONS";